on:
  pull_request:
    branches:
      - main

env:
  test_sheet_id: ${{ secrets.test_sheet_id }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby and Jekyll
      run: |
        sudo apt-get install -y ruby-full build-essential zlib1g-dev
        gem install --user-install jekyll bundler
    - run: pip install -r tests/test_requirements.txt
    - run: $HOME/.gem/ruby/3.0.0/bin/jekyll serve -B -s site
    - name: Set up service_account_credentials.json
      run: |
        echo '${{ secrets.service_account_credentials }}' > service_account_credentials.json
    - run: python -m unittest discover -s ./tests/
