on: 
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r tests/test_requirements.txt
    - run: python -m unittest discover -s ./tests/
  
