on: 
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install -r tests/test_requirements.txt
    - name: Set up service_account_credentials.json
      run: |
        echo "${{ secrets.service_account_credentials }}" > service_account_credentials.json
    - name: Set up .env
      run: |
        echo "${{ secrets.env }}" > .env
    - run: python -m unittest discover -s ./tests/
